FizzBuzz/FizzBuzz.Web/ViewModels/FizzBuzzViewModel.cs
using System.ComponentModel.DataAnnotations;
using FizzBuzz.BusinessFacade.Models;
using PagedList;

namespace FizzBuzz.Web.ViewModels
{
    /// <summary>
    /// Fizz buzz view model.
    /// </summary>
    public class FizzBuzzViewModel
    {
        /// <summary>
        /// Gets or sets the number.
        /// </summary>
        /// <value>
        /// The number.
        /// </value>
        [Required(ErrorMessage = "Please enter a number.")]
        [Range(1, 1000, ErrorMessage = "Enter a number between 1 and 1000.")]
        [Display(Name = "Enter a number.")]
        public int Number { get; set; }

        /// <summary>
        /// Gets or sets the fizz buzz result.
        /// </summary>
        /// <value>
        /// The fizz buzz result.
        /// </value>
        public PagedList<FizzBuzzModel> FizzBuzzResult { get; set; }
    }
}

FizzBuzz/FizzBuzz.Web/Controllers/FizzBuzzController.cs
using System.Web.Mvc;
using FizzBuzz.BusinessFacade.Generators;
using FizzBuzz.BusinessFacade.Models;
using FizzBuzz.Web.ViewModels;
using PagedList;

namespace FizzBuzz.Web.Controllers
{
    /// <summary>
    /// FizzBuzz mvc controller.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        // GET: /FizzBuzz/

        /// <summary>
        /// The fizz buzz generator
        /// </summary>
        private readonly IFizzBuzzOutputGenerator fizzBuzzGenerator;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController" /> class.
        /// </summary>
        /// <param name="fizzBuzzGenerator">The fizz buzz generator.</param>
        public FizzBuzzController(IFizzBuzzOutputGenerator fizzBuzzGenerator)
        {
            this.fizzBuzzGenerator = fizzBuzzGenerator;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var fizzBuzzViewModel = new FizzBuzzViewModel
            {
                Number = 1
            };
            return this.View(fizzBuzzViewModel);
        }

        /// <summary>
        /// Gets the fizz buzz list.
        /// </summary>
        /// <param name="input">The input.</param>
        /// <param name="pageNumber">The page number.</param>
        /// <param name="numberOfItems">The number of items.</param>
        /// <returns></returns>
        public ActionResult GetFizzBuzzResult(FizzBuzzViewModel input, int pageNumber = 1, int numberOfItems = 20)
        {
            var fizzBuzzOutput = this.fizzBuzzGenerator.Generate(new RangeModel
            {
                StartPoint = 1,
                EndPoint = input.Number
            });

            var fizzBuzzOutputWithPaging = new PagedList<FizzBuzzModel>(fizzBuzzOutput, pageNumber, numberOfItems);

            return this.View("Index", new FizzBuzzViewModel { Number = input.Number, FizzBuzzResult = fizzBuzzOutputWithPaging });
        }
    }
}

FizzBuzz/FizzBuzz.Web/Controllers/UserValuesController.cs
using System;
using System.Collections.Generic;
using System.Web.Http;

namespace FizzBuzz.Web.Controllers
{
    /// <summary>
    /// REST service to capture user entered values.
    /// </summary>
    public class UserValuesController : ApiController
    {
        // GET api/<UserValues>

        /// <summary>
        /// Gets items.
        /// </summary>
        /// <returns></returns>
        public IEnumerable<string> Get()
        {
            return null;//TODO:Due to time constraint unable to implement this.
        }

        // POST api/<UserValues>

        /// <summary>
        /// Posts the specified value.
        /// </summary>
        /// <param name="value">The value.</param>
        public void Post([FromBody] string value)
        {
            //Add logic to store user entered values
            new NotImplementedException();
        }
    }
}

FizzBuzz/FizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Web.ViewModels.FizzBuzzViewModel

@{
    ViewBag.Title = "Fizz Buzz";
}

<h2>Fizz Buzz</h2>
<div>

 @using (Html.BeginForm("GetFizzBuzzResult", "FizzBuzz"))
    {

       @Html.Partial("_FizzBuzzFormPartial", Model)
        
    }
    @Html.Partial("_FizzBuzzResultsPartial", Model)
</div>

FizzBuzz/FizzBuzz.Web/Views/FizzBuzz/_FizzBuzzFormPartial.cshtml
@model FizzBuzz.Web.ViewModels.FizzBuzzViewModel

<div>
    <div>
        @Html.LabelFor(model => model.Number)
        @Html.TextBoxFor(model => model.Number)
        @Html.ValidationMessageFor(model => model.Number)
        <input type="submit" id="button" value="Submit" />
    </div>
</div>

FizzBuzz/FizzBuzz.Web/Views/FizzBuzz/_FizzBuzzResultsPartial.cshtml
@using PagedList.Mvc
@model FizzBuzz.Web.ViewModels.FizzBuzzViewModel

@if (Model != null && Model.FizzBuzzResult != null && Model.FizzBuzzResult.Any())
{
    <section id="fizzBuzzResults">

        <div>
            <h2>FizzBuzz Results</h2>
            <ul>
                @foreach (var item in Model.FizzBuzzResult)
                {
                    <li>
                       @foreach (var description in @item.Description.Split(' '))
                       {
                           <span class="@description.ToLowerInvariant()">@description</span>
                       }
                    </li>
                }

            </ul>
            @if (@Model.FizzBuzzResult.PageCount > 1)
            {
                @Html.PagedListPager(Model.FizzBuzzResult, pageNumber => Url.Action("GetFizzBuzzResult", new {Number = Model.Number, pageNumber = pageNumber}))
                <span>Items @Model.FizzBuzzResult.FirstItemOnPage to @Model.FizzBuzzResult.LastItemOnPage of Total @Model.FizzBuzzResult.TotalItemCount</span>
            }
        </div>
    </section>

}

FizzBuzz/FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fizzbuzzbundle")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>